In [1]:
import numpy as np

In [2]:
def objective(position):
    
    no_attack_on_j = 0
    
    queen_not_attacking=0
    
    for i in range(len(position) - 1): 
        
        no_attack_on_j=0
        
        for j in range(i + 1, len(position)):
            
            if (position[j] != position[i]) and (position[j] != position[i] + (j - i)) and (position[j] != position[i] - (j - i)):
                
                no_attack_on_j += 1
                
                if(no_attack_on_j==len(position)-1-i):
                    
                    queen_not_attacking+=1

    if(queen_not_attacking==7):
        
        queen_not_attacking+=1
    
    return queen_not_attacking

In [3]:
def hill_climbing_for_nqueen(n):
    
    rand_sol=[]
    
    for i in range(n):
        
        rand_sol.append(np.random.randint(0,high=n))
    
    board = np.zeros((n,n))
    
    for i in range(n):
        
        board[i,rand_sol[i]] = 8
        
    print('starting game state= \n', board, '\n queens in peace = ', objective(rand_sol))
    
    best = rand_sol
    
    old_best = []
    
    while best != old_best :
        
        old_best = best
        
        s1 = best
        s2 = best
        s3 = best
        
        rand_num1 = np.random.randint(0,high=n)
        rand_num2 = np.random.randint(0,high=n)
        rand_num3 = np.random.randint(0,high=n)
        
        s1[np.random.randint(0,high=n)] = np.random.randint(0,high=n)
        
        s2[np.random.randint(0,high=n)] = np.random.randint(0,high=n)
        s2[np.random.randint(0,high=n)] = np.random.randint(0,high=n)
        
        s3[np.random.randint(0,high=n)] = np.random.randint(0,high=n)
        s3[np.random.randint(0,high=n)] = np.random.randint(0,high=n)
        s3[np.random.randint(0,high=n)] = np.random.randint(0,high=n)
        
        nn = max(objective(s1),objective(s2),objective(s3),objective(best))
        
        if nn == objective(s1):
            best = s1
        elif nn == objective(s2):
            best = s2
        elif nn == objective(s3):
            best = s3
            
    board = np.zeros((n,n))
    
    for i in range(n):
        
        board[i,best[i]] = 8
        
    print('\n Final game state =\n', board, '\n queens in peace = ', objective(best))

In [18]:
hill_climbing_for_nqueen(9)

starting game state= 
 [[0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0. 0.]] 
 queens in peace =  0

 Final game state =
 [[8. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0.]] 
 queens in peace =  3


In [19]:
hill_climbing_for_nqueen(8)

starting game state= 
 [[0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0.]] 
 queens in peace =  1

 Final game state =
 [[0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0.]] 
 queens in peace =  2


In [20]:
hill_climbing_for_nqueen(9)

starting game state= 
 [[0. 0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8.]] 
 queens in peace =  2

 Final game state =
 [[0. 0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8.]] 
 queens in peace =  2


In [21]:
hill_climbing_for_nqueen(9)

starting game state= 
 [[0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]] 
 queens in peace =  2

 Final game state =
 [[0. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]] 
 queens in peace =  3
